# Generated by Django 3.1.2 on 2023-06-26 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_lineapedido_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineapedido',
            name='estado',
        ),
    ]
