# Generated by Django 3.1.2 on 2023-07-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_remove_lineapedido_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSeguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguimiento', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='estado',
        ),
    ]
