# Generated by Django 3.1.2 on 2023-07-08 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_pedido_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='estado',
        ),
    ]
