# Generated by Django 3.1.2 on 2023-06-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_lineapedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineapedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
