# Generated by Django 3.1.2 on 2023-07-08 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_remove_pedido_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiposeguimiento',
            old_name='estado',
            new_name='seguimiento',
        ),
    ]
