# Generated by Django 3.1.2 on 2023-06-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_auto_20230625_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineapedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20),
        ),
    ]
