# Generated by Django 3.1.2 on 2023-07-08 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_auto_20230708_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='seguimiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pedidos.tiposeguimiento'),
        ),
    ]
